name: Tests-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0

        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          XDEBUG_MODE: coverage

        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true
